keys:
  - &djoolz age10k89krww75k7jp09atly6xay636673nwy66kwv5s3epupf4zl3lser84gy
  - &centauri age1hus8yrj5y6aa0fntqp8glv7pqxqnhczt8y0xhaxznxvk6e2s4vls5v2dcc
  - &mirach age1d860j0aa5d2fru0rfpyp4mxtyzwt6fw8crvlzerw542gqtfnnd3qfprgw2
creation_rules:
  - path_regex: ^secrets/users/djoolz/.*\.yaml$
    key_groups:
      - age:
          - *djoolz
          - *centauri
          - *mirach
  - path_regex: ^secrets/machines/centauri/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *djoolz
          - *centauri
  - path_regex: ^secrets/machines/mirach/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *djoolz
          - *mirach
  - path_regex: ^secrets/services/shared/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *djoolz
          - *centauri
          - *mirach
