keys:
  - &djoolz age10k89krww75k7jp09atly6xay636673nwy66kwv5s3epupf4zl3lser84gy
  - &djoolz_1 age1sepf5z006mt22nwftm9tgvhqxj4j3jmw4rapre290sze6ecyapeqzjjtle
  - &djoolz_2 age1x6l976f6qfq55gfw05qju3vegaa56q43d78mjmmzkv3qgc4z8ahqn9uz39
  - &albaldah age1hl3u09qjx5mz5939agcjpr8u0wecsu8vqcqn38ykeq2qswp6s4eqlhz9cq
  - &alhena age1089ktlqhw7fh82pps74m8upuxp2m2ljzl73ya9ujtyr8s8nf8e6s2u5gvh
  - &centauri age1hus8yrj5y6aa0fntqp8glv7pqxqnhczt8y0xhaxznxvk6e2s4vls5v2dcc
  - &mirach age1d860j0aa5d2fru0rfpyp4mxtyzwt6fw8crvlzerw542gqtfnnd3qfprgw2
creation_rules:
  - path_regex: ^secrets/users/djoolz/.*\.yaml$
    key_groups:
      - age:
          - *djoolz
          - *djoolz_1
          - *djoolz_2
          - *albaldah
          - *alhena
          - *centauri
          - *mirach

  - path_regex: ^secrets/services/crowdsec/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *djoolz
          - *djoolz_1
          - *djoolz_2
          - *albaldah

  - path_regex: ^secrets/services/fleet-test/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *djoolz
          - *djoolz_1
          - *djoolz_2
          - *albaldah
          - *alhena
          - *centauri
          - *mirach

  - path_regex: ^secrets/machines/albaldah/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *djoolz
          - *djoolz_1
          - *djoolz_2
          - *albaldah

  - path_regex: ^secrets/machines/alhena/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *djoolz
          - *djoolz_1
          - *djoolz_2
          - *alhena

  - path_regex: ^secrets/machines/centauri/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *djoolz
          - *djoolz_1
          - *djoolz_2
          - *centauri

  - path_regex: ^secrets/machines/mirach/.*\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *djoolz
          - *djoolz_1
          - *djoolz_2
          - *mirach