key: ENC[AES256_GCM,data:zFwmDgWYrUQEdV0I2Ywd/KZQfjMgSI5YtLLxtEYLV1agCWQl9oEk0xgjIw==,iv:YPpHsJx8ZMwztJoBa/il3esIdnkloxKCVllwVTI56ZI=,tag:ZmrUWgLYDYPZ2A3pGZfcfA==,type:str]
sops:
  age:
    - recipient: age10k89krww75k7jp09atly6xay636673nwy66kwv5s3epupf4zl3lser84gy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcHRrdlNJZlhxdFJYL1pD
        bVNSVUdwOGJ3V1FER3pNOFFoVThoNGZhemljCjd3alJ5K1RBRzYycHhvMTlSczl6
        S0NJUmkyWStnaHB5R1ZDdFNMWkoxZFUKLS0tIHZLY2ZVNnBZY1k2L0drcEJrSHVz
        ZHZyUkVoNTdyN2FZengrWUxWN0dmUW8KS3+yVQx5vn9XAKevEXOBIVJTzhsbgxgT
        QPHpb9ps/gYyiI/AABVe3iHXL0sfiuhP42S2KfN9xqN4cWYBfsOAfQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1sepf5z006mt22nwftm9tgvhqxj4j3jmw4rapre290sze6ecyapeqzjjtle
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQXFCakROQlpkSnYxZGNj
        ZWd6YmlzcHNFN0w5Q001bkZhRmlOTEpUcTFNCjZCejR3WlY3WmxNMWxFR0cvMUJM
        RjVNd0phdFkrMFlkcFltSkUwc2lwTFEKLS0tIGdwSEQxWC9YbDU4QXNCQVYzemRQ
        NC8xUENvTkkzYTRiNG4rNmNLT2tQMFkK+gC/yHTmC/eGWDHpw18MZa4Yv1J4VB7s
        NF1D+LZhSLbCNSETT+XJwT8fLmMpCUFIJa/OD7tGqxBJmNwUxXbd3A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1x6l976f6qfq55gfw05qju3vegaa56q43d78mjmmzkv3qgc4z8ahqn9uz39
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aEdXeVlsR2hja2J4T1U5
        cm44UHdkZWh4YVZZV2pJTSt6cGcwQVNDN2xVClRWZ2d6aCtWK2w2N2I4MUV6L3Mv
        RUtRLzhVcFFCNnpreFI0cHAvVkhkNWcKLS0tIFlmVzZUNERoZmluV0F3aGprOTZp
        ZStFV0tDYVVWd29BQndIWlpCbVpjM2MKo6JgNuzqKWppVzxdYji0WQQTJm01fcQx
        3RjYuJvhGKPiplHeErgejttquVZCnQhy4+odVdGTXEH76lJxtyTFYg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1hl3u09qjx5mz5939agcjpr8u0wecsu8vqcqn38ykeq2qswp6s4eqlhz9cq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPa1dZMHZ4WHhyTEYvcDR6
        VEVGTzB4aGd2aVRBRlEzTFBOOENyaEdoVlR3CkFQL1NmVmF1WGxtVHpDSUF4NVpp
        NzA0cGxMelhja1pGc1hwSWNjY1NIbGcKLS0tIHJmVm9VeDdhVTcvVFFqKytqZHJY
        MVRXNDJPVUR2Z1NPZVlkdE95aGZVQXcKip+RPDfd5A8deD0negA+dgjQAUkyvUbs
        iie04U+Zg5stBN9eTUzeiIzVcPrMX70Vof6LMozt08L3oWHrrxrdyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T10:44:18Z"
  mac: ENC[AES256_GCM,data:87fPfYQog4uqFx6zEKCju6l28oreUzXnsc4eyVektvmfdhljvsV4kSeOM3P8HMcgZUYxZ6cGUpxsjT42bFAlBjTSsLun0o4B35aCQZ5Hv7U2mqrHG32tJWQ6+D9Jg79gHNQBWBEAGYJkH88bASsvZhYDIvcl9KFQbpM/BHqsqjw=,iv:7zHNweI2S3YbTVWRrx+ROFFEYZ+Zj8VWe8nR1SIm+7w=,tag:7VCpvqN0tKkIDBn8Dat/Tg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
