# This is your home-manager configuration file
# Use this to configure your home environment (it replaces ~/.config/nixpkgs/home.nix)
{
  inputs,
  lib,
  config,
  pkgs,
  ...
}: {
  # You can import other home-manager modules here
  imports = [
    # If you want to use home-manager modules from other flakes (such as nix-colors):
    # inputs.nix-colors.homeManagerModule

    # You can also split up your configuration and import pieces of it here:
    # ./nvim.nix
  ];

  nixpkgs = {
    # You can add overlays here
    overlays = [
      # If you want to use overlays exported from other flakes:
      # neovim-nightly-overlay.overlays.default

      # Or define it inline, for example:
      # (final: prev: {
      #   hi = final.hello.overrideAttrs (oldAttrs: {
      #     patches = [ ./change-hello-to-hi.patch ];
      #   });
      # })
    ];
    # Configure your nixpkgs instance
    config = {
      # Disable if you don't want unfree packages
      allowUnfree = true;
      # Workaround for https://github.com/nix-community/home-manager/issues/2942
      allowUnfreePredicate = _: true;
    };
  };

  # TODO: Set your username
  home = {
    username = "djoolz";
    homeDirectory = "/home/djoolz";

    # language = {
    #   base = "en_US.UTF-8";
    #   address = "de_DE.UTF-8";
    #   collate = "de_DE.UTF-8";
    #   ctype = "de_DE.UTF-8";
    #   measurement ="de_DE.UTF-8";
    #   messages ="de_DE.UTF-8";
    #   monetary ="de_DE.UTF-8";
    #   name = "de_DE.UTF-8";
    #   numeric ="de_DE.UTF-8";
    #   paper = "de_DE.UTF-8";
    #   time = "de_DE.UTF-8";
    # };
  };

  # Add stuff for your user as you see fit:
  # programs.neovim.enable = true;
  home.packages = with pkgs; [ 
    curl
    htop
    btop
    # nixos-conf-editor
    # nix-software-center
    wget
    smartmontools
    ansible
    barrier # needs an open firewall port
    bitwarden
    # blender
    clinfo
    direnv
    # dnsmasq
    elfinfo
    moonlight-qt
    nextcloud-client
    gimp-with-plugins
    git
    glxinfo
    gparted
    inkscape
    # kicad
    libreoffice-qt6-still
    nix-tree
    # obs-studio
    # orca-slicer
    pciutils
    # prusa-slicer
    python312
    rustdesk
    spotify
    # super-slicer-latest
    synology-drive-client    
    syncthing # needs an open firewall port
    syncthingtray
    # tailscale # needs an open firewall port. FIXME duplicate?
    traceroute
    vlc
    # vscode
    vulkan-tools
    # wayland-info
    wireshark
    webcamoid
    xsane
  ];
  programs = {
    home-manager.enable = true;
    git.enable = true;
    firefox.enable = true;

    vscode = {
      enable = true;
      package = pkgs.vscode;#.fhs;
    };
    
    ## Works, but I want the latest version and not a beta.
    ## https://github.com/cideM/visual-studio-code-insiders-nix
    # vscode = {
    #   enable = true;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    #   package = (pkgs.vscode.override{ isInsiders = true; }).overrideAttrs (oldAttrs: rec {
    #     src = (builtins.fetchTarball {
    #       url = "https://update.code.visualstudio.com/latest/linux-x64/insiders";
    #       ## This sha246 could be automatically generated by nix-prefetch-url
    #       sha256 = "0kd30ydwn1bkaf5jmwwy5rb83jrpnd48saahacg0acn57100x1h7";
    #     });
    #     version = "latest";
    #   });
    # };

    # I didn't like vscodium at first sight ... 
    # vscode = {
    #   enable = true;
    #   package = pkgs.vscodium;
    #   # extensions = with pkgs.vscode-extensions; [
    #   #   dracula-theme.theme-dracula
    #   #   vscodevim.vim
    #   #   yzhang.markdown-all-in-one
    #   # ];
    # };
  };

  # Nicely reload system units when changing configs
  systemd.user.startServices = "sd-switch";

  # https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion
  home.stateVersion = "24.05";
}
